### ISSUE TITLE
StaticCountry API missing

### ISSUE THREAD

**Issue by Cruiser13** [j-mastr/sevdesk-api#52]
While we have the [Model](https://github.com/j-mastr/sevdesk-php-sdk/blob/main/lib/Model/ModelStaticCountryResponse.php), we do not have the API yet.
The endpoint should be located at /api/v2/StaticCountry (at least ehe v1 endpoint has been at /api/v1/StaticCountry).

**Comment by j-mastr** [comment]
Hi @Cruiser13,

Thank you for bringing this up. Could you please check if you are able to send requests to the endpoint in v2? Because I'm getting an error 404 when trying to call it.

**Comment by Cruiser13** [comment]
@j-mastr I'm getting a 404 too at the moment. May be offline or not available yet?

**Comment by j-mastr** [comment]
Okay, under these circumstances I'll close this for now, as long as it is not (yet) clear, if there will be any API at all.
